import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as v from "valibot";
import { GatrieverConfigSchema, type GatrieverConfig, PackageJsonConfigSchema } from "./config.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export interface PrepareResult {
  target: string;
  outDir: string;
  copiedBundles: string[];
  generatedFiles: string[];
}

export async function readProjectConfig(cwd = process.cwd()): Promise<GatrieverConfig> {
  const pkgPath = path.join(cwd, "package.json");
  try {
    const raw = await fs.readFile(pkgPath, "utf-8");
    const json = JSON.parse(raw);
    const parsed = v.parse(PackageJsonConfigSchema, json);
    return v.parse(GatrieverConfigSchema, parsed.gatriever || {});
  } catch {
    console.warn("⚠️ Could not read valid 'gatriever' configuration from package.json, using defaults.");
    return v.parse(GatrieverConfigSchema, {});
  }
}

/**
 * Finds the location of a pre-built cartridge file.
 * Prioritizes packaged dist/cartridges/ alongside this CLI file.
 */
async function resolveCartridgePath(appName: string, target: string, cwd: string): Promise<string> {
  const adapterName = target === "docker" ? "node" : target;
  const fileName = `${appName}.${adapterName}.js`;

  const possiblePaths = [
    // 1. Packaged inside CLI's own distribution folder (for installed npm package)
    path.resolve(__dirname, "cartridges", fileName),
    path.resolve(__dirname, "..", "cartridges", fileName),
    // 2. Relative to monorepo root (during internal dev / dogfooding)
    path.resolve(__dirname, "..", "..", "..", "apps", appName, "dist", fileName),
    path.resolve(cwd, "..", "..", "apps", appName, "dist", fileName),
    path.resolve(cwd, "apps", appName, "dist", fileName),
    // 3. From standard node_modules
    path.join(cwd, "node_modules", "gatriever", "dist", "cartridges", fileName),
    path.join(cwd, "node_modules", `@gatriever/${appName}`, "dist", fileName),
  ];

  for (const p of possiblePaths) {
    try {
      await fs.access(p);
      return p;
    } catch {
      // Continue searching
    }
  }

  throw new Error(
    `Could not locate cartridge '${fileName}' for application '${appName}'.\nSearched in:\n${possiblePaths.join("\n")}`
  );
}

export async function prepareDeployment(cwd = process.cwd(), optionsConfig?: Partial<GatrieverConfig>): Promise<PrepareResult> {
  const projectConfig = await readProjectConfig(cwd);
  const config: GatrieverConfig = { ...projectConfig, ...optionsConfig };

  const outDir = path.resolve(cwd, config.outDir || "deploy");
  await fs.mkdir(outDir, { recursive: true });

  const copiedBundles: string[] = [];
  const generatedFiles: string[] = [];

  const target = config.target || "firebase";
  const adapterName = target === "docker" ? "node" : target;

  const features = config.features || {};

  // 1. Telegram Bot
  if (features.bot) {
    const botCartridge = await resolveCartridgePath("telegram-bot", target, cwd);
    const destName = `telegram-bot.${adapterName}.js`;
    await fs.copyFile(botCartridge, path.join(outDir, destName));
    copiedBundles.push(destName);
  }

  // 2. REST API Server
  if (features.api) {
    const apiCartridge = await resolveCartridgePath("api-server", target, cwd);
    const destName = `api-server.${adapterName}.js`;
    await fs.copyFile(apiCartridge, path.join(outDir, destName));
    copiedBundles.push(destName);
  }

  // 3. DDNS Sync Daemon / Cron
  if (features.ddns && features.ddns.enabled) {
    const ddnsCartridge = await resolveCartridgePath("ddns-sync", target, cwd);
    const destName = `ddns-sync.${adapterName}.js`;
    await fs.copyFile(ddnsCartridge, path.join(outDir, destName));
    copiedBundles.push(destName);
  }

  // 4. Generate entry points based on Target
  if (target === "firebase") {
    const exportsStatements: string[] = [];

    if (features.bot) {
      exportsStatements.push(`import botHandler from "./telegram-bot.firebase.js";`);
      exportsStatements.push(`import { onRequest } from "firebase-functions/v2/https";`);
      exportsStatements.push(`export const telegramHook = onRequest(botHandler());`);
    }

    if (features.api) {
      exportsStatements.push(`import apiHandler from "./api-server.firebase.js";`);
      exportsStatements.push(`export const api = onRequest(apiHandler());`);
    }

    if (features.ddns && features.ddns.enabled) {
      const cronSchedule = features.ddns.cron || "*/15 * * * *";
      exportsStatements.push(`import ddnsHandler from "./ddns-sync.firebase.js";`);
      exportsStatements.push(`import { onSchedule } from "firebase-functions/v2/scheduler";`);
      exportsStatements.push(`export const ddnsSync = onSchedule("${cronSchedule}", (e) => ddnsHandler(e));`);
    }

    const indexFileContent = `// Auto-generated by gatriever CLI - do not edit directly\n` + exportsStatements.join("\n") + "\n";
    const indexPath = path.join(outDir, "index.js");
    await fs.writeFile(indexPath, indexFileContent, "utf-8");
    generatedFiles.push("index.js");
  } else if (target === "docker" || target === "node") {
    const dockerfileContent = `FROM node:24-alpine
WORKDIR /app
COPY . .
ENV NODE_ENV=production
CMD ["node", "${copiedBundles[0] || 'telegram-bot.node.js'}"]
`;
    const dockerfilePath = path.join(outDir, "Dockerfile");
    await fs.writeFile(dockerfilePath, dockerfileContent, "utf-8");
    generatedFiles.push("Dockerfile");
  }

  return {
    target,
    outDir,
    copiedBundles,
    generatedFiles,
  };
}
